name: Daily Commit Workflow

on:
  schedule:
    # Run daily at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: 24ds3000044@ds.study.iitm.ac.in - Update timestamp
      run: |
        echo "Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > daily_update.txt
        echo "Workflow run ID: ${{ github.run_id }}" >> daily_update.txt
        echo "Commit SHA: ${{ github.sha }}" >> daily_update.txt
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add daily_update.txt
        git commit -m "Daily update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push 