name: Daily Commit Workflow

on:
  schedule:
    # Run daily at 9:00 AM UTC (cron syntax: minute hour day month day-of-week)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Step with email 24ds3000044@ds.study.iitm.ac.in
      run: |
        echo "This step contains the email 24ds3000044@ds.study.iitm.ac.in in its name"
        echo "Current timestamp: $(date)"
        
    - name: Create daily commit
      run: |
        # Create a simple log file with timestamp
        echo "Daily commit executed at $(date)" >> daily-log.txt
        echo "GitHub Action run ID: ${{ github.run_id }}" >> daily-log.txt
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add and commit the changes
        git add daily-log.txt
        git commit -m "Daily commit: $(date '+%Y-%m-%d %H:%M:%S UTC')"
        
    - name: Push changes
      run: |
        git push 